name: Docs

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        toolchain:
          - stable
          - beta
          - nightly
        precision: ["", "f32"]

    steps:
      - uses: actions/checkout@v3
      - name: Update
        run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - name: Update Git Submodules
        run: |
          git submodule update --init --remote --recursive
      - name: Build documentation
        run: |
          cargo doc --features=${{ matrix.precision }}
          cargo test --doc --features=${{ matrix.precision }}
