name: Docs

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        precision: ["", "f32"]

    steps:
      - uses: actions/checkout@v3
      - name: Update
        run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - name: Update Git Sumbodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
      - name: Build documentation
        run: |
          cargo doc --features=${{ matrix.precision }}
          cargo test --doc --features=${{ matrix.precision }}
