name: Examples

on:
  push:
    branches: ["main", "next"]
  pull_request:
    branches: ["main", "next"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        toolchain:
          - stable
          - beta
          - nightly
        precision: ["", "f32"]
        example:
          - entanglement
          - grovers_search

    steps:
      - uses: actions/checkout@v3
      - name: Update
        run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - name: Update Git Sumbodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
      - name: Run example ${{ matrix.example }}
        run: |
          cargo run --example ${{ matrix.example }} --features=${{ matrix.precision }}
      - name: Run example ${{ matrix.example }}  (release)
        run: |
          cargo run --release --example ${{ matrix.example }} --features=${{ matrix.precision }}
