name: Examples

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        example:
          - measure_first

    steps:
      - uses: actions/checkout@v3
      - name: Update
        run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - name: Update Git Sumbodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
      - name: Run example ${{ matrix.example }}
        run: |
          cargo run --example ${{ matrix.example }}
      - name: Run example ${{ matrix.example }}  (release)
        run: |
          cargo run --release --example ${{ matrix.example }}
