name: Format

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        toolchain:
          - nightly

    steps:
      - uses: actions/checkout@v3
      - name: Update
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
          rustup component add rustfmt
      - name: Format
        run: |
          cargo fmt --check --verbose
