name: Rust

on:
  push:
    branches: [ "main", "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Update Git Sumbodule
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --tests --verbose
