name: Test_f32

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3
      - name: Update
        run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - name: Update Git Sumbodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
      - name: Build with build script
        run: |
          cargo build --verbose --features=f32
      - name: Run unit tests
        run: |
          cargo test --verbose --features=f32
      - name: Build with build script (release)
        run: |
          cargo build --verbose --release --features=f32
      - name: Run unit tests (release)
        run: |
          cargo test --verbose --release --features=f32
