name: Test

on:
  push:
    branches: ["main", "next"]
  pull_request:
    branches: ["main", "next"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        toolchain:
          - stable
          - beta
          - nightly
        precision: ["", "f32"]

    steps:
      - uses: actions/checkout@v3
      - name: Update
        run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - name: Update Git Sumbodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
      - name: Build with build script
        run: |
          cargo build --verbose --features=${{ matrix.precision }}
      - name: Run unit tests
        run: |
          cargo test --verbose --features=${{ matrix.precision }}
      - name: Build with build script (release)
        run: |
          cargo build --verbose --release --features=${{ matrix.precision }}
      - name: Run unit tests (release)
        run: |
          cargo test --verbose --release --features=${{ matrix.precision }}
